version: 1
accounts:
  - name: user1
    mnemonic: "tomato father silver rebuild volume guard donor tattoo spike staff want inherit diagram wrap teach furnace spring squeeze tuition march card foil random west"
    coins: [
      "100000000stake", 
      "20invitesuper",
      "50invite0",
      "50invite1",
      "150invite2",
      "150invite3",
    ]
  - name: user2
    mnemonic: "liberty pass grain minute silent green crazy come pitch undo soup liberty bone flush exchange ladder gap grocery key load must panther honey person"
validator:
  name: user1
  staked: "1000000stake"
